# Generated by Django 2.2.7 on 2020-03-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NASA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('summary', models.TextField()),
                ('added_ts', models.DateTimeField(auto_now_add=True)),
                ('published', models.CharField(max_length=255)),
                ('article_id', models.CharField(max_length=255)),
                ('author_img_url', models.CharField(blank=True, max_length=255, null=True)),
                ('article_img_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
