# Generated by Django 2.2.7 on 2020-03-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_spacedotcom'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacedotcom',
            name='article_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
