# Generated by Django 2.2.7 on 2020-03-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_spacedotcom_article_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nasa',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='spacedotcom',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
